config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'

  resources :chats
  resources :users

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/register', to: 'sessions#register'

  get '/rooms/form', to: 'rooms#form'
  resources :rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user, foreign_key: :sender_id
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_and_belongs_to_many :members, class_name: 'User', foreign_key: :room_id, association_foreign_key: :member_id

  PERSONAL = 'personal'.freeze
  CHANNEL = 'channel'.freeze

  enum room_type: { personal: PERSONAL, channel: CHANNEL }, _prefix: true
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :rooms, class_name: 'Room', foreign_key: :member_id, association_foreign_key: :room_id

  def create_user_and_access(user, user_access)
    ActiveRecord::Base.transaction do
      user = User.create!(user)

      user_access = UserAccess.new(user_access)
      user_access.user_id = user.id
      user_access.save!
    end

    [user, user_access]
  end
end

app/models/user_access.rb
class UserAccess < ApplicationRecord
  belongs_to :user
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def authenticate_user!
    redirect_to login_path unless helpers.logged_in?
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @user = helpers.current_user
    @room = Room.find(params[:room_id])
    @chats = Chat.where(room_id: @room.id)

    @members = @room.members.filter { |member| member.id != @user.id }

    render 'list'
  end

  def create
    return if chat_params[:message].empty?

    user = helpers.current_user

    chat = Chat.new(chat_params)
    chat.sender_id = user.id

    ChatsChannel.broadcast_to(chat.room, chat) if chat.save
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @user = helpers.current_user

    @items = helpers.get_formatted_room_rows(@user.rooms)

    render 'list'
  end

  def form
    @users = User.where.not(id: session[:user_id])

    render 'form'
  end

  def create
    sender = helpers.current_user
    receiver = User.find(room_member_params[:room_member])

    room = Room.create(room_params)
    room.members.push(sender)
    room.members.push(receiver)

    redirect_to rooms_path
  end

  def room_params
    params.require(:room).permit(:room_type)
  end

  def room_member_params
    params.require(:room).permit(:room_member)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!

  def login
    if helpers.logged_in?
      redirect_to rooms_path
    else
      render 'login'
    end
  end

  def create
    user_access = UserAccess.find_by(user_access_username_params)

    if !!user_access && user_access.authenticate(user_access_password_params[:password])
      session[:user_id] = user_access.user_id
      redirect_to rooms_path
    else
      message = 'Username and Password combination is invalid'
      redirect_to login_path, notice: message
    end
  end

  def destroy
    reset_session
    redirect_to login_path
  end

  private

  def user_access_username_params
    params.require(:user_access).permit(:username)
  end

  def user_access_password_params
    params.require(:user_access).permit(:password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!

  def create
    _user, _user_access = User.create_user_and_access(user_params, user_access_params)

    redirect_to login_path
  rescue ActiveRecord::RecordNotUnique
    message = 'Username already exists'
    redirect_to register_path, notice: message
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end

  def user_access_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def get_formatted_room_rows(rooms)
    items = []
    rooms.each do |room|
      item = {
        text: format(
          '[%<room_type>s] %<room_members>s',
          room_type: room.room_type,
          room_members: room.members.map { |member| member.name }.join(' - ')
        ),
        room_id: room.id
      }
      items.push(item)
    end

    items
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def logged_in?
    !!session[:user_id]
  end

  def current_user
    @user ||= User.find_by_id(session[:user_id]) if !!session[:user_id]
  end
end

app/views/chats/list.html.erb
<div>
  <h2><%= @members.map { |member| member.name }.join(" - ") %></h2>

  <div id="chat_list">
    <% if @chats.blank? %>
      <p id="no_message">..... No message .....</p>
    <% else %>
      <% @chats.each do |c| %>
        <ul>
          <% if c.sender_id == @user.id %>
            ..........
          <% end %>
          <%= c.message %>
        </ul>
      <% end %>
    <% end %>
  </div>

  <%= form_with model: Chat.new do |form| %>
    <label for="chat_message">Message</label>:
    <%= form.text_field :message %>
    <%= form.hidden_field :room_id, value: @room.id %>
    <%= form.hidden_field :user_id, value: @user.id %>
    <%= form.submit "Submit", data: { disable_with: false } %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsChatApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= action_cable_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/rooms/form.html.erb
<div>
  <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>

  <h2>Register</h2>
  <%= form_with model: Room.new do |form| %>
    <label for="room_type">Type</label>:
    <%= form.select :room_type, options_for_select(Room.room_types) %><br>
    <label for="room_member">Type</label>:
    <%= form.select :room_member, options_for_select(@users.map { |user| [user.name, user.id] }) %><br>
    <%= form.submit "Create" %><br>
  <% end %>
</div>

app/views/rooms/list.html.erb
<div>
  <h2>Room List</h2>

  <div id="room_list">
    <% if @items.blank? %>
      <p id="no_room">..... No room .....</p>
    <% else %>
      <% @items.each do |i| %>
        <ul><%= link_to i[:text], chats_path(room_id: i[:room_id]) %></ul>
      <% end %>
    <% end %>
  </div>

  <div>
    <%= link_to "Create New Room", controller: :rooms, action: :form %>
  </div>

  <br>

  <div>
    <%= link_to "Log Out", logout_path, method: :delete %>
  </div>
</div>